Repository UnBArqDsw/2020.1_G13_iGado, pull requests merged in 2020-10, with the labels that each got.

#75 72 Refatorar Lexicos
  docs/Product/Lexicons.md
Labels: Documentação, Melhoria, Requisitos

#77 Refatorar Design Sprint
  docs/Product/DesignSprint/Brainstorming.md
  docs/Product/DesignSprint/DesignSprint.md
  docs/Product/DesignSprint/HighFidelityPrototype.md
  docs/Product/MindMap.md
Labels: Design Sprint, Documentação, Melhoria

#79 Refatoração dos Custos
  docs/Project/CostManagementPlan.md
Labels: Documentação, Melhoria

#87 86 - Estudo sobre GoFs Comportamentais
  _sidebar.md
  docs/Assets/Img/Studies/GoFs/ChainOfResponsibility.png
  docs/Assets/Img/Studies/GoFs/Command.png
  docs/Assets/Img/Studies/GoFs/Iterator.png
  docs/Assets/Img/Studies/GoFs/Mediator.png
  docs/Assets/Img/Studies/GoFs/Memento.png
  docs/Assets/Img/Studies/GoFs/Observer.png
  docs/Assets/Img/Studies/GoFs/State.png
  docs/Assets/Img/Studies/GoFs/Strategy.png
  docs/Assets/Img/Studies/GoFs/TemplateMethod.png
  docs/Assets/Img/Studies/GoFs/Visitor.png
  docs/Studies/BehaviorGoF.md
Labels: Documentação, PadroesDeProjetos, hacktoberfest-accepted

#84 82 padroes de projeto emergentes
  _sidebar.md
  docs/Assets/Img/Studies/EmergingDesignPatterns/CompositePatternExample.png
  docs/Assets/Img/Studies/EmergingDesignPatterns/FactoryMethodPatternExample.png
  docs/Assets/Img/Studies/EmergingDesignPatterns/SingletonPattern.png
  docs/Assets/Img/Studies/EmergingDesignPatterns/StatePatternExample.png
  docs/Studies/EmergingDesignPatterns.md
Labels: Documentação, PadroesDeProjetos, hacktoberfest-accepted

#92 80 - Documentar Sprint
  _sidebar.md
  docs/SprintsAndMeetings/2020-09-26-Sprint5Opening.md
  docs/SprintsAndMeetings/2020-10-03-Sprint5Closure.md
  docs/SprintsAndMeetings/2020-10-03-Sprint6Opening.md
Labels: Documentação, hacktoberfest-accepted

#90 83 - Elaboração estudo dirigido GoFs Estruturais
  _sidebar.md
  docs/Studies/BehaviorGoF.md
  docs/Studies/EmergingDesignPatterns.md
  docs/Studies/StructuralGofs.md
Labels: Arquitetura, Documentação, PadroesDeProjetos, hacktoberfest-accepted

#89 88 - Estudo sobre GoFs Criacionais
  _sidebar.md
  docs/Studies/CreationalGoF.md
Labels: Documentação, PadroesDeProjetos, hacktoberfest-accepted

#94 85 Estudo dirigido sobre GRASP
  _sidebar.md
  docs/Studies/GRASP.md
Labels: PadroesDeProjetos, hacktoberfest-accepted

#93 91 - Documentar Sprint 6
  .gitignore
  _sidebar.md
  docs/Assets/Img/Sprints/BurnDownSprint6.png
  docs/Assets/Img/Sprints/VelocitySprint6.png
  docs/SprintsAndMeetings/2020-10-10-Sprint6Closure.md
  docs/SprintsAndMeetings/2020-10-10-Sprint7Opening.md
Labels: Documentação, hacktoberfest-accepted

#115 105 - Documentação da Sprint
  _sidebar.md
  docs/Assets/Img/Sprints/BurnDownSprint7.png
  docs/Assets/Img/Sprints/VelocitySprint7.png
  docs/SprintsAndMeetings/2020-10-17-Sprint7Closure.md
  docs/SprintsAndMeetings/2020-10-17-Sprint8Opening.md
Labels: Documentação, hacktoberfest-accepted

#117 HOTFIX: Fix images in behavior gof document
  docs/Studies/BehaviorGoF.md
Labels: Melhoria, PadroesDeProjetos, bug

#116 81 - Dojo de flutter
  _sidebar.md
  docs/Assets/Img/Studies/DojoFlutter/LoginScreenTree.png
  docs/Assets/Img/Studies/DojoFlutter/RegisterScreenTree.png
  docs/Assets/Img/Studies/DojoFlutter/SplashScreenTree.png
  docs/Studies/DojoFlutter.md
Labels: Documentação, PadroesDeProjetos, hacktoberfest-accepted

#118 110 - Refatoração do diagrama de atividades.
  docs/Modeling/ActivityDiagram.md
Labels: Documentação, Melhoria, Modelagem, hacktoberfest-accepted

#119 111 - Refatoração do diagrama de Comunicação/Colaboração
  docs/Modeling/ColaborationDiagram.md
Labels: Documentação, Melhoria, Modelagem, hacktoberfest-accepted

#120 107 - Refatorar Diagrama Classes
  docs/Assets/Img/Modeling/ClassDiagram/ClassDiagramV1.2.png
  docs/Modeling/ClassDiagram.md
Labels: Documentação, hacktoberfest-accepted

#121 Refatorar Diagramas de Estado
  docs/Assets/Img/Modeling/StateDiagram/CattleStateDiagramV1.1.png
  docs/Assets/Img/Modeling/StateDiagram/CattleStateDiagramV1.png
  docs/Assets/Img/Modeling/StateDiagram/ReportStateDiagramV1.1.png
  docs/Assets/Img/Modeling/StateDiagram/ReportStateDiagramV1.png
  docs/Assets/Img/Modeling/StateDiagram/UserAuthStateDiagramV1.1.png
  docs/Assets/Img/Modeling/StateDiagram/UserAuthStateDiagramV1.png
  docs/Modeling/StateDiagram.md
Labels: Documentação, Melhoria, Modelagem

#125 108 - Refatorar Diagrama de Componentes
  docs/Assets/Img/Modeling/ComponentsDiagram/ComponentsDiagram2.png
  docs/Modeling/ComponentsDiagram.md
Labels: Documentação, Melhoria, hacktoberfest-accepted

#126 HOTFIX - Atualiza estudo dirigido de GoFs Criacionais na wiki
  docs/Assets/Img/Studies/GoFs/Creational/creational.png
  docs/Assets/Img/Studies/GoFs/Creational/creational1.png
  docs/Assets/Img/Studies/GoFs/Creational/creational2.png
  docs/Assets/Img/Studies/GoFs/Creational/creational3.png
  docs/Assets/Img/Studies/GoFs/Creational/creational4.png
  docs/Assets/Img/Studies/GoFs/Creational/creational5.png
  docs/Assets/Img/Studies/GoFs/Creational/creational6.png
  docs/Studies/CreationalGoF.md
Labels: Documentação, Melhoria, PadroesDeProjetos, hacktoberfest-accepted

#124 HOTFIX - Adição dos vídeos gravados à wiki
  docs/SprintsAndMeetings/2020-08-29-Sprint1Opening.md
  docs/SprintsAndMeetings/2020-09-19-Sprint4Opening.md
  docs/SprintsAndMeetings/2020-10-10-Sprint7Opening.md
  docs/SprintsAndMeetings/2020-10-17-Sprint8Opening.md
  docs/Studies/BehaviorGoF.md
  docs/Studies/CreationalGoF.md
  docs/Studies/EmergingDesignPatterns.md
  docs/Studies/GRASP.md
  docs/Studies/StructuralGofs.md
Labels: Documentação, Melhoria, enhancement, hacktoberfest-accepted

#127 123 - Documentação dos padrões de projetos aplicados
  .vscode/settings.json
  _sidebar.md
  docs/Assets/Img/DesignPatterns/BehaviorGoFs/IteratorExample.png
  docs/Assets/Img/DesignPatterns/BehaviorGoFs/MementoExample.jpg
  docs/Assets/Img/DesignPatterns/BehaviorGoFs/StateExample.png
  docs/Assets/Img/DesignPatterns/BehaviorGoFs/TemplateMethodExample.jpg
  docs/Assets/Img/DesignPatterns/BehaviorGoFs/TemplateMethodExample2.png
  docs/Assets/Img/DesignPatterns/BehaviorGoFs/TemplateMethodExample3.png
  docs/Assets/Img/DesignPatterns/CreationalGoFs/FactoryMethodExample.png
  docs/Assets/Img/DesignPatterns/CreationalGoFs/SingletonExample.png
  docs/Assets/Img/DesignPatterns/GRAPS/BovinePolimorfism.png
  docs/Assets/Img/DesignPatterns/GRAPS/CohesionModelFarm.png
  docs/Assets/Img/DesignPatterns/GRAPS/ControllerServices.png
  docs/Assets/Img/DesignPatterns/GRAPS/DairyCattle.png
  docs/Assets/Img/DesignPatterns/GRAPS/EspecialistService.png
  docs/Assets/Img/DesignPatterns/GRAPS/OwnInvestmentServices.png
  docs/Assets/Img/DesignPatterns/GRAPS/PolimorfismExample.png
  docs/Assets/Img/DesignPatterns/GRAPS/ReportPolimorfism.png
  docs/Assets/Img/DesignPatterns/StructuralGoFs/FacadeExample.png
  docs/DesignPatterns/BehaviorGoFs.md
  docs/DesignPatterns/CreationalGoFs.md
  docs/DesignPatterns/GRASP.md
  docs/DesignPatterns/StructuralGoFs.md
  docs/SprintsAndMeetings/2020-10-26-Sprint8Closure.md
  docs/SprintsAndMeetings/2020-10-26-Sprint9Opening.md
Labels: Documentação, PadroesDeProjetos, hacktoberfest-accepted
