Repository UnBArqDsw/2020.1_G13_iGado, pull requests merged in 2020-11, with the labels that each got.

#134 Refatoração do Diagrama de Pacotes
  docs/Assets/Img/Modeling/PackageDiagram/PackageDiagramV2.0.png
  docs/Modeling/PackageDiagram.md
Labels: Melhoria, Modelagem

#135 Refatoração do Diagrama de Sequências
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-CadastroDeBovinoV2.png
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-EstoqueDeInsumosV2.png
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-ManejoV2.png
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-RegistroELoginV2.png
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-RelatórioV2.png
  docs/Modeling/SequenceDiagram.md
Labels: Documentação, Modelagem

#140 139 - Documentar fechamento da Sprint 9 e aberturda da Sprint 10
  _sidebar.md
  docs/Assets/Img/Sprints/BurnDownSprint9.png
  docs/Assets/Img/Sprints/VelocitySprint9.png
  docs/SprintsAndMeetings/2020-11-02-Sprint10Opening.md
  docs/SprintsAndMeetings/2020-11-02-Sprint9Closure.md
Labels: Documentação

#150 149 - Documentar fechamento da sprint 10 e abertura sprint 11
  _sidebar.md
  docs/Assets/Img/Sprints/BurnDownSprint10.png
  docs/Assets/Img/Sprints/VelocitySprint10.png
  docs/SprintsAndMeetings/2020-11-09-Sprint10Closure.md
  docs/SprintsAndMeetings/2020-11-09-Sprint11Opening.md
Labels: Design Sprint

#155 136 - Criação do Documento de Arquitetura
  _sidebar.md
  docs/Assets/Img/Project/ArchitectureDocument/ArchitecturalRepresentation.png
  docs/Assets/Img/Project/ArchitectureDocument/CattleModule.png
  docs/Assets/Img/Project/ArchitectureDocument/ManagementModule.png
  docs/Assets/Img/Project/ArchitectureDocument/ReportModule.png
  docs/Assets/Img/Project/ArchitectureDocument/nfr.png
  docs/Project/ArchitectureDocument.md
Labels: Arquitetura, Documentação

#162 154 - Documentar fechamento da Sprint 11 e Abertura da Sprint 12
  _sidebar.md
  docs/Assets/Img/Sprints/BurdownSprint11.png
  docs/Assets/Img/Sprints/VelocitySprint11.png
  docs/SprintsAndMeetings/2020-11-16-Sprint11Closure.md
  docs/SprintsAndMeetings/2020-11-16-Sprint12Opening.md
Labels: Documentação
