Repository UnBArqDsw/2020.1_G13_iGado, pull requests merged in 2020-09, with the labels that each got.

#14 #5 - Elaboração do 5W2H
  _sidebar.md
  docs/product/5w2h.md
Labels: Documentação, Pré-rastreabilidade

#16 15 - Change site visual
  _coverpage.md
  _sidebar.md
  docs/assets/img/logo/background.png
  docs/assets/img/logo/logo.png
  index.html
Labels: Melhoria, Product Owner

#17 10 - Add Mind Map document to wiki
  _sidebar.md
  docs/assets/img/artefacts/mind_map.png
  docs/product/MindMap.md
Labels: Design Sprint, Documentação, Requisitos

#18 #6 Add Ishikawa Diagram document to wiki
  _sidebar.md
  docs/assets/img/artefacts/ishikawa_diagram.png
  docs/product/IshikawaDiagram.md
Labels: Documentação, Requisitos

#20 12 - Design Sprint
  README.md
  _coverpage.md
  _sidebar.md
  docs/.nojekyll
  docs/Assets/Css/home.css
  docs/Assets/Img/Artefacts/Brainstorming.png
  docs/Assets/Img/Artefacts/BrainstormingColor1.png
  docs/Assets/Img/Artefacts/BrainstormingColor2.png
  docs/Assets/Img/Artefacts/BrainstormingColor3.png
  docs/Assets/Img/Artefacts/BrainstormingColor4.png
  docs/Assets/Img/Artefacts/BrainstormingColors.png
  docs/Assets/Img/Artefacts/BrainstormingGroup.png
  docs/Assets/Img/Artefacts/IshikawaDiagram.png
  docs/Assets/Img/Artefacts/MindMap.png
  docs/Assets/Img/Artefacts/RichPictureGeral.png
  docs/Assets/Img/Artefacts/Splash.png
  docs/Assets/Img/Logo/Background.png
  docs/Assets/Img/Logo/Logo.png
  docs/Assets/Img/Misc/CommitExample.gif
  docs/Assets/Img/Product/Team/CaioVinicius.jpg
  docs/Assets/Img/Product/Team/GuilhermeMendes.jpg
  docs/Assets/Img/Product/Team/IuriSevero.jpg
  docs/Assets/Img/Product/Team/JoaoPedro.jpg
  docs/Assets/Img/Product/Team/LucasFellipe.jpg
  docs/Policies/Branches.md
  docs/Policies/Commits.md
  docs/Policies/Issues.md
  docs/Policies/Policies.md
  docs/Policies/PullRequests.md
  docs/Product/5W2H.md
  docs/Product/DesignSprint/Brainstorming.md
  docs/Product/DesignSprint/DesignSprint.md
  docs/Product/DesignSprint/HighFidelityPrototype.md
  docs/Product/DesignSprint/RichPicture.md
  docs/Product/DesignSprint/StoryBoard.md
  docs/Product/IshikawaDiagram.md
  docs/Product/MindMap.md
  docs/README.md
  docs/index.html
  docs/product/MindMap.md
  index.html
Labels: Design Sprint, Documentação

#25 #21 - Elaboração do Plano de Gerenciamento de Riscos e Plano de Comunicação
  _sidebar.md
  docs/Assets/Img/Project/EAR.jpg
  docs/Product/DesignSprint/Brainstorming.md
  docs/Product/DesignSprint/HighFidelityPrototype.md
  docs/Product/DesignSprint/RichPicture.md
  docs/Project/CommunicationManagementPlan.md
  docs/Project/RiskManagementPlan.md
Labels: Documentação

#27 24 - Elaborar BPMN
  _sidebar.md
  docs/Product/BPMN.md
Labels: Documentação

#30 #26 - Criar documento de Léxicos
  _sidebar.md
  docs/Product/Lexicons.md
Labels: Documentação

#28 #23 - Criar documento de metodologia
  _sidebar.md
  docs/Product/5W2H.md
  docs/Product/BPMN.md
  docs/Product/Lexicons.md
  docs/Product/Methodology.md
  docs/Project/CommunicationManagementPlan.md
  docs/Project/RiskManagementPlan.md
Labels: Documentação

#34 #31 Elaborar Backlog do Produto
  _sidebar.md
  docs/Project/ProductBacklog.md
Labels: Documentação

#35 #4 Elaborar Documento de Visão
  _sidebar.md
  docs/Product/VisionDocument.md
Labels: Documentação

#37 36 - Documentação do questionário
  README.md
  _coverpage.md
  _sidebar.md
  docs/Assets/Img/Logo/Icon.png
  docs/Product/Questionary.md
Labels: Documentação, Melhoria

#38 33 - documentar reuniões na wiki
  _sidebar.md
  docs/SprintsAndMeetings/2020-08-21-RequirementsElicitationTechniquesAndTechnologies.md
  docs/SprintsAndMeetings/2020-08-24-Sprint0Opening.md
  docs/SprintsAndMeetings/2020-08-29-Sprint0Closure.md
  docs/SprintsAndMeetings/2020-08-29-Sprint1Opening.md
  docs/SprintsAndMeetings/2020-09-02-DesignSprintAndMethodology.md
  docs/SprintsAndMeetings/2020-09-05-Sprint1Closure.md
  docs/SprintsAndMeetings/2020-09-05-Sprint2Opening.md
  docs/SprintsAndMeetings/MeetingModel.md
  docs/SprintsAndMeetings/SprintClosureModel.md
  docs/SprintsAndMeetings/SprintOpeningModel.md
  docs/SprintsAndMeetings/SprintsAndMeetings.md
Labels: Documentação

#40 #39 Elaborar documento de Entrevista
  _sidebar.md
  docs/Project/Interview.md
Labels: Documentação

#41 22 - Elaboração dos Plano de Gerenciamento de Custos
  _sidebar.md
  docs/Product/5W2H.md
  docs/Product/Questionary.md
  docs/Product/VisionDocument.md
  docs/Project/CostManagementPlan.md
  docs/Project/Interview.md
Labels: Documentação, Melhoria

#47 45 - Documentar fechamento da Sprint 2 e Abertura da Sprint 3
  docs/Assets/Img/Sprints/BurnDownSprint2.png
  docs/Assets/Img/Sprints/VelocitySprint2.png
  docs/SprintsAndMeetings/2020-08-24-Sprint0Opening.md
  docs/SprintsAndMeetings/2020-08-29-Sprint0Closure.md
  docs/SprintsAndMeetings/2020-08-29-Sprint1Opening.md
  docs/SprintsAndMeetings/2020-09-02-DesignSprintAndMethodology.md
  docs/SprintsAndMeetings/2020-09-05-Sprint1Closure.md
  docs/SprintsAndMeetings/2020-09-05-Sprint2Opening.md
  docs/SprintsAndMeetings/2020-09-12-Sprint2Closure.md
  docs/SprintsAndMeetings/2020-09-12-Sprint3Opening.md
Labels: Documentação

#51 49 - Priorização do Backlog
  _sidebar.md
  docs/Project/BacklogPrioritization.md
Labels: Documentação

#53 44 - Elaboração do Diagrama Entidade Relacionamento
  _sidebar.md
  docs/Assets/Img/Modeling/DatabaseModeling/DER_v1.png
  docs/Modeling/DatabaseModeling.md
Labels: Documentação, Modelagem

#56 54 - Elaborar Diagrama de Pacotes
  _sidebar.md
  docs/Assets/Img/Modeling/DiagramPackage/PackageDiagramBackendV1.png
  docs/Assets/Img/Modeling/DiagramPackage/PackageDiagramFrontV2.png
  docs/Assets/Img/Modeling/DiagramPackage/PackageDiagramFrontendV1.png
  docs/Modeling/PackageDiagram.md
Labels: Documentação, Modelagem

#59 #50 Elaboração do Diagrama de Classes
  _sidebar.md
  docs/Modeling/ClassDiagram.md
  docs/Modeling/DatabaseModeling.md
Labels: Documentação, Modelagem

#58 Diagrama de Sequência
  _sidebar.md
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-CadastroDeBovino.png
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-EstoqueDeInsumos.png
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-Manejo.png
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-RegistroELogin.png
  docs/Assets/Img/Modeling/SequenceDiagram/SequenceDiagram-Relatório.png
  docs/Modeling/SequenceDiagram.md
Labels: Documentação, Modelagem

#60 Matriz de Relações
  _sidebar.md
  docs/Product/RelationsMatrix.md
Labels: Documentação

#62 52 - Documentar Sprint
  _sidebar.md
  docs/Assets/Img/Sprints/BurnDownSprint3.png
  docs/Assets/Img/Sprints/VelocitySprint3.png
  docs/SprintsAndMeetings/2020-09-05-Sprint2Opening.md
  docs/SprintsAndMeetings/2020-09-12-Sprint2Closure.md
  docs/SprintsAndMeetings/2020-09-19-Sprint3Closure.md
  docs/SprintsAndMeetings/2020-09-19-Sprint4Opening.md
Labels: Documentação

#63 61 Documentar Fechamento da Sprint 4 e Abertura da Sprint 5
  _sidebar.md
  docs/Assets/Img/Sprints/BurnDownSprint4.png
  docs/Assets/Img/Sprints/VelocitySprint4.png
  docs/SprintsAndMeetings/2020-09-26-Sprint4Closure.md
  docs/SprintsAndMeetings/2020-09-26-Sprint5Opening.md
Labels: Documentação

#67 HOTFIX - Adicionando imagens de versões antigas do diagrama de classe
  docs/Assets/Img/Modeling/ClassDiagram/ClassDiagramV0.1.png
  docs/Assets/Img/Modeling/ClassDiagram/ClassDiagramV0.2.png
  docs/Assets/Img/Modeling/ClassDiagram/ClassDiagramV1.png
  docs/Modeling/ClassDiagram.md
Labels: Documentação, Melhoria

#66 65 - Criação dos diagramas de atividades
  _sidebar.md
  docs/Modeling/ActivityDiagram.md
Labels: Documentação, Modelagem

#71 68 - Elaboração do Diagrama de Estados
  _sidebar.md
  docs/Modeling/StateDiagram.md
  docs/SprintsAndMeetings/2020-09-26-Sprint4Closure.md
Labels: Documentação, Modelagem

#69 64 diagrama de componentes
  _sidebar.md
  docs/Assets/Img/Modeling/ComponentsDiagram/ComponentsDiagram.png
  docs/Assets/Img/Modeling/ComponentsDiagram/ComponentsDiagramDraft.jpg
  docs/Modeling/ComponentsDiagram.md
Labels: Documentação, Modelagem

#73 Elaboração do Diagrama de Colaboração
  _sidebar.md
  commit
  docs/Assets/Img/Modeling/ColaborationDiagram/BovineManagement.png
  docs/Assets/Img/Modeling/ColaborationDiagram/GenerateReport.png
  docs/Assets/Img/Modeling/ColaborationDiagram/Insumos.png
  docs/Modeling/ColaborationDiagram.md
Labels: Documentação, Modelagem
